### ISSUE TITLE
Could not set StatusBar style to dark-content with Immersive.on

### ISSUE THREAD

**Issue by serjek** [mockingbot/react-native-immersive#12]
Could not set StatusBar style to dark-content. It always forces to light-content, even setting StatusBar style directly blinks it's style to dark and then immediately switches to light.

**Comment by ThatBean** [comment]
With `Immersive.on()` successfully enabled, there should be no visible StatusBar or NavBar.

You may want to re-check the [Basic Usage](https://github.com/mockingbot/react-native-immersive#basic-usage), and ReactNative Document: [StatusBar](https://facebook.github.io/react-native/docs/statusbar.html).

**Comment by serjek** [comment]
Hello, thanks for swift reply! Yes basically header and navbar should be removed if immersive is on, but I'm talking about cases when header is visible during immersive (swipe from top, keyboard show, alert or modal etc). Apparently I switched from immersive to always-show mode for better UX, so won't be able to provide details. I would close the issue.
