### ISSUE TITLE
Problem configuring project with gradle:2.3

### ISSUE THREAD

**Issue by arsimr16** [mockingbot/react-native-immersive#15]
When I try to build my Android app, I'm getting the following error: 

![image](https://user-images.githubusercontent.com/5560545/49767681-54057700-fc8e-11e8-9958-77d573e10a55.png)

It seems like jcenter can't find any versions of gradle.  When I add maven, gradle is found, but not the correct version.

```buildscript {
    repositories {
        maven {
            url "https://maven.google.com"
        }
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.+'
    }
}
```

![image](https://user-images.githubusercontent.com/5560545/49767794-cfffbf00-fc8e-11e8-98f6-b97ed3093f9d.png)

Changing the gradle version in the classpath to 3.1.4 fixed this issue for me.  Did anyone else have this problem?

**Comment by rogerkerse** [comment]
Same problem

**Comment by rogerkerse** [comment]
Created pull request for it https://github.com/mockingbot/react-native-immersive/pull/18

**Comment by ThatBean** [comment]
@arsimr16 thanks for reporting this, and @rogerkerse @TechWithYou thanks for the pull request.

After some digging, the problem starts with: 
> Google request JCenter to remove several binaries from their repository (2018/12/10)
> But some more repos were removed by mistake

check:
- https://stackoverflow.com/a/53729300
- https://github.com/oblador/react-native-vector-icons/issues/605

The `build.gradle` is updated as [react-native-vector-icons/android/build.gradle](https://github.com/oblador/react-native-vector-icons/blob/2cab96eb99d6e33598465d40b6a2fbacf9369886/android/build.gradle)
