### ISSUE TITLE
immersive is disabled after opening modal or coming back from sleep

### ISSUE THREAD

**Issue by yanush** [mockingbot/react-native-immersive#4]
After opening a modal window, the immersive mode is disabled.
I had to reactivate it after closing the modal window.
Same thing happens when the application comes back from sleep mode

**Comment by ThatBean** [comment]
Sorry for the late reply. 

We want to keep this module simple, and keep the state of immersive mode in JavaScript.
For the mode reset when application comes back from sleep mode, try using `AppState` like this from ReactNative Docs:

```js
class Root extends PureComponent {
  constructor (props) {
    super (props)

    this.setImmersiveOn = () => {
      Immersive.on()
      this.setState({ isImmersive: true })
    }
    this.setImmersiveOff = () => {
      Immersive.off()
      this.setState({ isImmersive: false })
    }
    this.onAppStateChange = (nextAppState) => {
      nextAppState === 'active' && console.log('App has come to the foreground!')
      nextAppState === 'active' && this.state.isImmersive && Immersive.on()
    }

    this.state = { isImmersive: false }
  }

  componentDidMount() { AppState.addEventListener('change', this.onAppStateChange) }

  componentWillUnmount() { AppState.removeEventListener('change', this.onAppStateChange) }

  render() {
    return <View style={styles.container}>
      <Button onPress={this.setImmersiveOn} title="Immersive on" />
      <Button onPress={this.setImmersiveOff} title="Immersive off" />
    </View>
  }
}
```

**Comment by alimek** [comment]
but what about modal, it makes sense for me to reactivate it when app changed state, but what about modal ? @ThatBean

**Comment by ThatBean** [comment]
Haven't tried modal in our project yet. But with our experience, the Immersive Flag will get reset on: 

- coming back to active AppState:
      - fix: `AppState.addEventListener('change', (state) => state === 'active' && Immersive.on())`

- after the Keyboard dismiss:
      - fix: `Keyboard.addListener('keyboardDidHide', Immersive.on)`

- after Alert opening
      - fix: `Immersive.on` in `onDismiss` and all `onPress`, or somthing less good like `setTimeout(Immersive.on, 200)`

- after Modal opening (haven't tried in our project yet)

--- --- --- ---

In our case, we combine the reset with StatusBar and use something like this:

```js
const setLayoutStatus = PLATFORM_ANDROID ? ({ isHideStatusBar = false, isImmersive = false }) => {
  __DEV__ && console.log('[setLayoutStatus]', { isHideStatusBar, isImmersive })
  StatusBar.setHidden(isHideStatusBar)
  StatusBar.setTranslucent(true)
  StatusBar.setBackgroundColor('#00000066', true)
  Immersive.setImmersive(isImmersive)
} : () => {}
```

**Comment by alimek** [comment]
OK, thanks :)

**Comment by ThatBean** [comment]
@yanush  @alimek  you might want to try `react-native-immersive@1.1.0` and check out [Restore Immersive State](https://github.com/mockingbot/react-native-immersive#restore-immersive-state).

**Comment by alimek** [comment]
great :) thanks

**Comment by Jacky9425** [comment]
any idea what does the immersive listener do? cause if we can use default component listeners to control the immersive flag, then why there is a immersive listener?

**Comment by ghost** [comment]
Hi @ThatBean 
Have you tried using it with Modals?
I'm facing a problem when using it with Modals.
Help me out please.

**Comment by thakkarnetram** [comment]
> Hi @ThatBean Have you tried using it with Modals? I'm facing a problem when using it with Modals. Help me out please.
Same problem
