### ISSUE TITLE
could this work in Expo builds ¿?

### ISSUE THREAD

**Issue by Viral-Inc** [mockingbot/react-native-immersive#7]
could this work in Expo builds ¿?

**Comment by ThatBean** [comment]
Just checked the Expo Doc, and I think it may need to `detach` Expo and use **basic** React Native.
From Expo: 

> **But no native modules…**
> The most limiting thing about Expo is that you can’t add in your own native modules without `detaching` and using ExpoKit.

This is an Android native module for React Native. 
And we currently have not tried Expo yet.

You might want to check Expo Doc for similar API or 
[how-do-i-add-custom-native-code-to-my-expo-project](https://docs.expo.io/versions/latest/introduction/faq.html#how-do-i-add-custom-native-code-to-my-expo-project)

**Comment by Viral-Inc** [comment]
righto, thank you for the reply
