### ISSUE TITLE
Working with Modals

### ISSUE THREAD

**Issue by ascorbic** [mockingbot/react-native-immersive#8]
Hi,
Is there a way of getting this to work with Modals?

**Comment by ThatBean** [comment]
Do you mean the Immersive State do not last after Modal open? You can check [Restore Immersive State](https://github.com/mockingbot/react-native-immersive#restore-immersive-state).

And the [Sample Component](https://github.com/mockingbot/react-native-immersive#sample-component) covers most of the basic usage

**Comment by ascorbic** [comment]
No, I mean is there a way of keeping it in immersive mode while the modal is open? It restores fine after the modal closes, but while the modal is open the soft buttons and system bar appear.

**Comment by ThatBean** [comment]
I guess that's a bit more difficult.

Just googled a bit and this [stackoverflow](https://stackoverflow.com/questions/22794049/how-do-i-maintain-the-immersive-mode-in-dialogs) seems to have the answer.

I'm not good at native Android, but I think to keep immersive mode during Modal, we may need to customize the code for creating the Modal.
On Android which should be a `android.app.Dialog`, and we should change the Java code to make the Dialog non-focusable. [src](https://github.com/facebook/react-native/pull/5320)

For our React Native app, we used zIndex & elevation to create Model like UI, and skipped the actual Modal component.

**Comment by HRCJ7** [comment]
@ascorbic and @ThatBean  Have you found any solution for this?

**Comment by ascorbic** [comment]
@HRCJ7 No, I never did.
