### ISSUE TITLE
It doesn't work with Modal

### ISSUE THREAD

**Issue by EIgnatenko** [mockingbot/react-native-immersive#9]
Hello. In general it successfully work with wix-react-native-router. But, it doesn't work if I use screen as a modal. Version of react-native-router is latest. Could you give any idea, how can I handle it.

**Comment by ThatBean** [comment]
About Modal, you might want check the [restore-immersive-state](https://github.com/mockingbot/react-native-immersive#restore-immersive-state) section in README.md,
or this previous issue #4
